# /templates/l4-udp-forward.yml
udp:
  routers:
    vless-xhttp:
      entryPoints: [l4udp]                     # :443/udp
      service: vless-xhttp-svc

  services:
    vless-xhttp-svc:
      loadBalancer:
        servers:
          - address: "3x-ui:${PORT_LOCAL_XHTTP}"  # xray UDP inbound (Vision/QUIC)
