# templates/lampac.yml

http:
  services:
    lampac-service:
      loadBalancer:
        servers:
          - url: "http://lampac:${PORT_LAMPAC}"
        passHostHeader: true
    warp-plus:
      loadBalancer:
        servers:
          - url: "http://warp-plus:1080"

  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowHeaders:
          - Origin
          - Content-Type
          - Accept
        accessControlAllowCredentials: true

  routers:
    lampac-ws:
      rule: "Host(`${WEBDOMAIN}`) && Path(`/ws`)"
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - secured
      service: lampac-service
      priority: 10

    lampac-proxy:
      rule: "Host(`${WEBDOMAIN}`) && PathPrefix(`/proxy`)"
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - secured
      service: warp-plus
      priority: 5

    lampac:
      rule: "Host(`${WEBDOMAIN}`) && (PathPrefix(`/`))"
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - secured
      service: lampac-service
      priority: 1

