# dynamic/lampac.yml

http:  
  routers:  
    lampac-main:  
      rule: "Host(`${WEBDOMAIN}`)"  
      service: lampac-service  
      middlewares:  
        - lampac-headers  
        - lampac-cors  
      tls:  
        certResolver: le
      entryPoints:  
        - websecure
      priority: 900 
    
    lampac-proxy:    
      rule: "Host(`${WEBDOMAIN}`) && (PathPrefix(`/proxy/`) || PathPrefix(`/proxy-dash/`))"    
      service: lampac-service    
      middlewares:    
        - lampac-headers    
        - lampac-proxy-headers    
      tls:  
        certResolver: le
      entryPoints:  
        - websecure
      priority: 901  # Proxy маршруты  
        
    lampac-images:    
      rule: "Host(`${WEBDOMAIN}`) && PathPrefix(`/proxyimg`)"    
      service: lampac-service    
      middlewares:    
        - lampac-headers    
        - lampac-image-headers    
      tls:  
        certResolver: le
      entryPoints:  
        - websecure 
      priority: 902  # Изображения  

    lampac-websocket:  
      rule: "Host(`${WEBDOMAIN}`) && Path(`/ws`)"  
      service: lampac-service  
      middlewares:  
        - lampac-headers  
      tls:  
        certResolver: le
      entryPoints:  
        - websecure
      priority: 903  # WebSocket

  services:  
    lampac-service:  
      loadBalancer:  
        servers:  
          - url: "http://lampac:9118"
  
  middlewares:  
    lampac-headers:  
      headers:  
        customRequestHeaders:  
          X-Forwarded-Proto: "https"  
          X-Forwarded-For: ""  
          X-Real-IP: ""  
        customResponseHeaders:  
          Access-Control-Allow-Credentials: "true"  
          Access-Control-Allow-Private-Network: "true"  
          Access-Control-Allow-Methods: "POST, GET, OPTIONS"  
          Access-Control-Allow-Headers: "Accept, Origin, Content-Type, Authorization, X-Requested-With, X-Signalr-User-Agent, Cache-Control, DNT, If-Modified-Since, Keep-Alive, User-Agent, Token, Profile"  
  
    lampac-cors:  
      headers:  
        accessControlAllowOriginList:  
          - "*"  
        accessControlAllowCredentials: true  
        accessControlAllowMethods:  
          - "GET"  
          - "POST"  
          - "OPTIONS"  
        accessControlMaxAge: 86400  
  
    lampac-cache-control:  
      headers:  
        customResponseHeaders:  
          Cache-Control: "no-cache, no-store, must-revalidate"  
          Pragma: "no-cache"  
          Expires: "0"
          
    lampac-proxy-headers:  
      headers:  
        customRequestHeaders:  
          X-Forwarded-Proto: "https"  
          X-Real-IP: ""  
  
    lampac-image-headers:  
      headers:  
        customResponseHeaders:  
          Cache-Control: "public, max-age=3600"