http:
  routers:
    lampac-preflight:
      rule: "Host(`${WEBDOMAIN}`) && Method(`OPTIONS`)"
      entryPoints:
        - websecure
      middlewares:
        - lampac-cors-response
      service: noop@internal
      priority: 100

    lampac-proxy:
      rule: "Host(`${WEBDOMAIN}`) && (PathPrefix(`/proxy/`) || PathPrefix(`/proxy-dash/`))"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-cors-response   # CORS для реальных запросов
        - lampac-proxy-headers   # если нужны доп. request-заголовки
        - lampac-security
      priority: 90

    lampac-scripts:
      rule: "Host(`${WEBDOMAIN}`) && PathRegexp(`^/(lampainit|sisi|lite|online|tmdbproxy|cubproxy|tracks|dlna|timecode|ts)\\.js`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-scripts-cache   # длинный кэш для версионированных js
        - lampac-security
      priority: 80

    lampac-images:
      rule: "Host(`${WEBDOMAIN}`) && PathPrefix(`/proxyimg`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-image-headers
        - lampac-security
      priority: 70

    lampac-websocket:
      rule: "Host(`${WEBDOMAIN}`) && PathPrefix(`/ws`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-security
      priority: 60

    lampac-main:
      rule: "Host(`${WEBDOMAIN}`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-security
      priority: 50

  services:
    lampac-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://lampac:9118"
        # healthCheck:
        #   path: /health
        #   interval: "10s"
        #   timeout: "3s"

  middlewares:
    lampac-headers:
      headers:
        # УБРАНО затирание IP. Traefik сам заполнит X-Forwarded-For/Proto/Host корректно.
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    # Для старых/неверсионированных скриптов оставь no-cache, иначе используй это
    lampac-scripts-cache:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000, immutable"

    # Если нужно полностью отключить кэш (как было)
    lampac-cache-control:
      headers:
        customResponseHeaders:
          Cache-Control: "no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "0"

    lampac-proxy-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          # X-Real-IP / X-Forwarded-For не трогаем

    lampac-image-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=86400"  # было 3600, можно вернуть если нужно

    lampac-cors-response:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
          Access-Control-Allow-Headers: "Authorization, Content-Type, X-Requested-With"
          Access-Control-Max-Age: "86400"
          Vary: "Origin"

    lampac-security:  
      headers:  
        stsSeconds: 31536000  
        stsIncludeSubdomains: true  
        stsPreload: true  
        browserXssFilter: true  
        contentTypeNosniff: true  
        frameDeny: false  
        # frameOptions не указываем для максимальной свободы  
        referrerPolicy: "no-referrer-when-downgrade"  # Более мягкая политика  
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
        
# (необязательно) В static config Traefik:
# tls:
#   options:
#     modern:
#       minVersion: VersionTLS12
#       sniStrict: true
# и затем в каждом роутере:
#   tls:
#     options: modern@file
