# dynamic/lampac.yml

http:
  routers:
    lampac-main:
      rule: "Host(`${WEBDOMAIN}`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
      priority: 1

    lampac-websocket:
      rule: "Host(`${WEBDOMAIN}`) && Path(`/ws`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
      priority: 2

    lampac-images:
      rule: "Host(`${WEBDOMAIN}`) && PathPrefix(`/proxyimg`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-image-headers
      priority: 3

    lampac-scripts:
      rule: "Host(`${WEBDOMAIN}`) && PathRegexp(`^/(lampainit|sisi|lite|online|tmdbproxy|cubproxy|tracks|dlna|timecode|ts)\\.js`)"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-cache-control
      priority: 3

    lampac-proxy:
      rule: "Host(`${WEBDOMAIN}`) && (PathPrefix(`/proxy/`) || PathPrefix(`/proxy-dash/`))"
      service: lampac-service
      entryPoints:
        - websecure
      tls:
        certResolver: le
      middlewares:
        - lampac-headers
        - lampac-proxy-headers
      priority: 4

    lampac-preflight:
      rule: "Host(`${WEBDOMAIN}`) && Method(`OPTIONS`)"
      entryPoints:
        - websecure
      middlewares:
        - lampac-proxy-headers
      service: noop@internal
      priority: 5

  services:
    lampac-service:
      loadBalancer:
        servers:
          - url: "http://lampac:9118"

  middlewares:
    lampac-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-For: ""
          X-Real-IP: ""

    lampac-cache-control:
      headers:
        customResponseHeaders:
          Cache-Control: "no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "0"

    lampac-proxy-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Real-IP: ""

    lampac-image-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=3600"