# secured chain: default-whitelist → default-headers → crowdsec@docker → error-pages@docker
http:
  middlewares:
    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
          - crowdsec-bouncer
          - error-pages