services:
  caddy:
    image: torotin/caddy-l4:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
    mem_limit: 512m
    cpus: "0.5"
    hostname: ${WEBDOMAIN}
    networks:
      - traefik-proxy
      - dns-net
    # dns:
    #   - 172.31.0.53
    volumes:
      - /opt/docker-proxy/_logs/caddy:/var/log/caddy
      - /opt/docker-proxy/caddy/config:/etc/caddy
      - /opt/docker-proxy/caddy/subs:/srv/subs:ro
      # - /opt/docker-proxy/caddy/site:/srv
    env_file:
      - /opt/docker-proxy/.env
    security_opt:
      - no-new-privileges=true
    # labels:
    #   - traefik.enable=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:2019/config | grep -q '\"apps\"' || nc -z 127.0.0.1 ${PORT_LOCAL_CADDYWEB}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
