services:
  caddy:
    image: torotin/caddy-l4:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
    mem_limit: 512m
    cpus: "0.5"
    hostname: ${WEBDOMAIN}
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.5
      dns-net:
        ipv4_address: 172.19.0.5
    # dns:
    #   - 172.19.0.10
    volumes:
      - /opt/docker-proxy/_logs/caddy:/var/log/caddy
      - /opt/docker-proxy/caddy/config:/etc/caddy
      - /opt/docker-proxy/caddy/subs:/srv/subs:ro
      # - /opt/docker-proxy/caddy/site:/srv
    env_file:
      - /opt/docker-proxy/.env
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:2019/config | grep -q '\"apps\"' || nc -z 127.0.0.1 ${PORT_LOCAL_CADDYWEB}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.tags=traefik

      # ---------- Service ----------
      # Caddy error backend + health-check
      - traefik.http.services.caddy-error.loadbalancer.server.port=${PORT_LOCAL_CADDYWEB}
      - traefik.http.services.caddy-error.loadbalancer.healthcheck.path=/index.html
      - traefik.http.services.caddy-error.loadbalancer.healthcheck.interval=10s
      - traefik.http.services.caddy-error.loadbalancer.healthcheck.timeout=2s

      # ---------- Middlewares ----------
      # Лимитирование запросов
      - traefik.http.middlewares.rate-limit.ratelimit.average=50
      - traefik.http.middlewares.rate-limit.ratelimit.burst=100

      # Сжатие
      - traefik.http.middlewares.compress.compress=true

      # Поддержка кастомных error pages
      - traefik.http.middlewares.error-pages.errors.status=400-599
      - traefik.http.middlewares.error-pages.errors.service=caddy-error
      - traefik.http.middlewares.error-pages.errors.query=/index.html

      # Перезапись Location для редиректов — направляем в Caddy
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.0.header=Location
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.0.regex=^https?://(${WEBDOMAIN})(/.*)?$
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.0.replacement=$2
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.1.header=Location
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.1.regex=^//(${WEBDOMAIN})(/.*)?$
      - traefik.http.middlewares.redirect-to-caddy.plugin.traefik-plugin-rewrite-headers.rewrites.1.replacement=$2

      # Цепочки middleware
      # Статические файлы — compress
      - traefik.http.middlewares.static-chain.chain.middlewares=compress

      # Основная цепочка для catch-all — error pages + редиректы
      - traefik.http.middlewares.caddy-chain.chain.middlewares=bouncer@file,error-pages,redirect-to-caddy,compress

      # ---------- Routers ----------
      # favicon обрабатываем через статическую цепочку
      - traefik.http.routers.caddy-favicon.rule=Host(`${WEBDOMAIN}`) && Path(`/favicon.ico`)
      - traefik.http.routers.caddy-favicon.entrypoints=websecure
      - traefik.http.routers.caddy-favicon.middlewares=static-chain
      - traefik.http.routers.caddy-favicon.tls.certresolver=le
      - traefik.http.routers.caddy-favicon.priority=1
      - traefik.http.routers.caddy-favicon.service=caddy-error

      # Общий catch-all роутер — передаём всё в Caddy
      - traefik.http.routers.caddy-catchall.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`/`)
      - traefik.http.routers.caddy-catchall.entrypoints=websecure
      - traefik.http.routers.caddy-catchall.middlewares=caddy-chain
      - traefik.http.routers.caddy-catchall.tls.certresolver=le
      - traefik.http.routers.caddy-catchall.priority=-1
      - traefik.http.routers.caddy-catchall.service=caddy-error
