services:
  traefik-acme-exporter:
    image: alpine:latest
    container_name: traefik-acme-exporter
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    security_opt:
      - no-new-privileges=true
      
    volumes:
      - ../traefik/acme.json:/acme.json:ro
      - ../traefik/pem:/export
      - ../traefik/exporter.sh:/usr/local/bin/exporter.sh:ro

    entrypoint: ["/bin/sh", "/usr/local/bin/exporter.sh"]

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "jq -e '.process == \"running\" and .status != \"ERROR\"' /home/health.json >/dev/null 2>&1"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
