services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - /opt/docker-proxy/.env
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_BASE=/${URI_DOZZLE}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - traefik-proxy
      - dns-net
    # dns:
    #   - 172.31.0.53
    security_opt:
      - no-new-privileges=true
