services:
  3x-ui:
    image: torotin/3x-ui:latest
    container_name: 3x-ui
    hostname: ${WEBDOMAIN}
    restart: always
    depends_on:
      traefik:
        condition: service_healthy
      warp:
        condition: service_healthy
      adguard:
        condition: service_healthy
      tor-proxy:
        condition: service_healthy
    tty: true
    security_opt:
      - no-new-privileges=true
    networks:
      traefik-proxy:
      dns-net:
    dns:
      - 172.31.0.53
    volumes:
      - /opt/docker-proxy/3x-ui/scripts/00_BeforeStart:/mnt/sh/beforestart
      - /opt/docker-proxy/3x-ui/scripts/01_AfterStart:/mnt/sh/afterstart
      - /opt/docker-proxy/3x-ui/configs/x-ui.db:/etc/x-ui/x-ui.db:rw
      - /opt/docker-proxy/3x-ui/configs/config.json:/app/bin/config.json:rw
      - /opt/docker-proxy/_logs/xray/access.log:/app/access.log
      - /opt/docker-proxy/_logs/xray/error.log:/app/error.log
      - /opt/docker-proxy/_logs:/var/log:rw
    env_file:
      - /opt/docker-proxy/.env
      - /opt/docker-proxy/3x-ui/3x-ui.env
    environment:
      # - XUI_LOG_LEVEL=debug
      - XUI_LOG_FOLDER=/var/log/3x-ui
    device_cgroup_rules:
      - 'c 10:200 rwm'
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      # 1) проверяем, что панель жива по admin-порту (PORT_LOCAL_VLESS_PANEL или 2053 по умолчанию)
      # 2) если панель отключена, хотя бы убедимся, что процесс жив (pgrep)
      test: ["CMD-SHELL", "curl -fsS 127.0.0.1:$PORT_LOCAL_VLESS_PANEL/$URI_PANEL_PATH/ >/dev/null || nc -z 127.0.0.1 ${PORT_LOCAL_VISION} || pgrep -f 'x-ui|xray|sing-box' >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
