services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    networks:
      traefik-proxy:
      dns-net:
        ipv4_address: 172.31.0.53
    # DNS service ports (uncomment if 53 is free on host)
    # ports:
    #   - "53:53/udp"
    #   - "53:53/tcp"
    volumes:
      - /opt/docker-proxy/adguard/work:/opt/adguardhome/work
      - /opt/docker-proxy/adguard/conf:/opt/adguardhome/conf
      - /opt/docker-proxy/adguard/update-pass.sh:/opt/adguardhome/update-pass.sh:ro
    env_file:
      - /opt/docker-proxy/.env
    security_opt:
      - no-new-privileges=true
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        apk add --no-cache bind-tools curl
        if [ -f /opt/adguardhome/update-pass.sh ]; then
          sh /opt/adguardhome/update-pass.sh || echo "[adguard-entrypoint] password update skipped"
        fi
        exec /opt/adguardhome/AdGuardHome -s run --config /opt/adguardhome/conf/AdGuardHome.yaml --work-dir /opt/adguardhome/work
    healthcheck:
      test: ["CMD-SHELL", "dig @127.0.0.1 -p 53 example.com +short | grep -q '.'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
