services:
  tor-proxy:
    container_name: tor-proxy
    image: peterdavehello/tor-socks-proxy:latest
    restart: unless-stopped
    # ports:
    ## SOCKS
    #   - 127.0.0.1:9150:9150/tcp
    ## DNS
    #   - 127.0.0.1:8853:8853/tcp
    healthcheck:
      test: >
        curl --fail --silent --socks5-hostname tor-proxy:9150 https://check.torproject.org/api/ip
        | grep '"IsTor":true'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - traefik-proxy
      - dns-net
    # dns:
    #   - 172.31.0.53
    security_opt:
      - no-new-privileges=true
