services:
  3x-ui:
    image: torotin/3x-ui:latest
    container_name: 3x-ui
    hostname: ${WEBDOMAIN}
    restart: always
    depends_on:
      traefik:
        condition: service_healthy
      warp:
        condition: service_healthy
      adguard:
        condition: service_healthy
      tor-proxy:
        condition: service_healthy
    tty: true
    security_opt:
      - no-new-privileges=true
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.12
      dns-net:
        ipv4_address: 172.19.0.12
    dns:
      - 172.19.0.10
    volumes:
      - /opt/docker-proxy/3x-ui/scripts/00_BeforeStart:/mnt/sh/beforestart
      - /opt/docker-proxy/3x-ui/scripts/01_AfterStart:/mnt/sh/afterstart
      - /opt/docker-proxy/3x-ui/configs/x-ui.db:/etc/x-ui/x-ui.db:rw
      - /opt/docker-proxy/3x-ui/configs/config.json:/app/bin/config.json:rw
      - /opt/docker-proxy/_logs/xray/access.log:/app/access.log
      - /opt/docker-proxy/_logs/xray/error.log:/app/error.log
      - /opt/docker-proxy/_logs:/var/log:rw
    env_file:
      - ./.env
      - /opt/docker-proxy/3x-ui/3x-ui.env
    environment:
      # - XUI_LOG_LEVEL=debug
      - XUI_LOG_FOLDER=/var/log/3x-ui
    device_cgroup_rules:
      - 'c 10:200 rwm'
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      # 1) проверяем, что панель жива по admin-порту (PORT_LOCAL_VLESS_PANEL или 2053 по умолчанию)
      # 2) если панель отключена, хотя бы убедимся, что процесс жив (pgrep)
      test: ["CMD-SHELL", "curl -fsS 127.0.0.1:$PORT_LOCAL_VLESS_PANEL/$URI_PANEL_PATH/ >/dev/null || nc -z 127.0.0.1 ${PORT_LOCAL_VISION} || pgrep -f 'x-ui|xray|sing-box' >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.tags=traefik

      # ---------- Сервисы ----------
      # Панель управления 3XUI
      - traefik.http.services.3xui-panel-svc.loadbalancer.server.port=${PORT_LOCAL_VLESS_PANEL}
      - traefik.http.services.3xui-panel-svc.loadbalancer.healthcheck.path=/${URI_PANEL_PATH}/
      - traefik.http.services.3xui-panel-svc.loadbalancer.healthcheck.interval=30s
      - traefik.http.services.3xui-panel-svc.loadbalancer.healthcheck.timeout=5s

      # Подписки
      - traefik.http.services.3xui-sub-svc.loadbalancer.server.port=${PORT_LOCAL_VLESS_SUBSCRIBE}

      # XHTTP
      - traefik.http.services.xhttp3xui-svc.loadbalancer.server.port=${PORT_LOCAL_XHTTP}

      # ---------- Middleware ----------
      # Сжатие
      - traefik.http.middlewares.3xui-compress.compress=true

      # Лимитирование запросов
      - traefik.http.middlewares.3xui-rate-limit.ratelimit.average=50
      - traefik.http.middlewares.3xui-rate-limit.ratelimit.burst=100

      # Цепочки middleware
      - traefik.http.middlewares.3xui-sub-chain.chain.middlewares=3xui-static-chain
      - traefik.http.middlewares.3xui-panel-chain.chain.middlewares=3xui-api-chain
      - traefik.http.middlewares.3xui-static-chain.chain.middlewares=3xui-compress
      - traefik.http.middlewares.3xui-api-chain.chain.middlewares=3xui-rate-limit,3xui-compress

      # ---------- Роутеры (HTTPS) ----------

      # Health-чек панели
      - traefik.http.routers.3xui-health.rule=Host(`${WEBDOMAIN}`) && Path(`/${URI_PANEL_PATH}/health`)
      - traefik.http.routers.3xui-health.entrypoints=websecure
      - traefik.http.routers.3xui-health.tls.certresolver=le
      - traefik.http.routers.3xui-health.service=3xui-panel-svc
      - traefik.http.routers.3xui-health.priority=9995

      # Раздача assets
      - traefik.http.routers.3xui-assets.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`/assets/`)
      - traefik.http.routers.3xui-assets.entrypoints=websecure
      - traefik.http.routers.3xui-assets.middlewares=bouncer@file,3xui-static-chain
      - traefik.http.routers.3xui-assets.tls.certresolver=le
      - traefik.http.routers.3xui-assets.service=3xui-sub-svc
      - traefik.http.routers.3xui-assets.priority=9996

      # Панель администратора
      - traefik.http.routers.3xui-panel.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`/${URI_PANEL_PATH}`)
      - traefik.http.routers.3xui-panel.entrypoints=websecure
      - traelfik.http.routers.3xui-panel.middlewares=bouncer@file,3xui-panel-chain
      - traefik.http.routers.3xui-panel.tls.certresolver=le
      - traefik.http.routers.3xui-panel.service=3xui-panel-svc
      - traefik.http.routers.3xui-panel.priority=9997

      # Подписки и JSON-эндпоинты
      - traefik.http.routers.3xui-sub.rule=Host(`${WEBDOMAIN}`) && (PathPrefix(`${URI_SUB_PATH}`) || PathPrefix(`${URI_JSON_PATH}`))
      - traefik.http.routers.3xui-sub.entrypoints=websecure
      - traefik.http.routers.3xui-sub.middlewares=bouncer@file,3xui-sub-chain
      - traefik.http.routers.3xui-sub.tls.certresolver=le
      - traefik.http.routers.3xui-sub.service=3xui-sub-svc
      - traefik.http.routers.3xui-sub.priority=9998

      # L4-режим для xhttp (TCP)
      - traefik.http.routers.xhttp3xui-l4.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`${URI_VLESS_XHTTP}`)
      - traefik.http.routers.xhttp3xui-l4.entrypoints=l4tcp
      - traefik.http.routers.xhttp3xui-l4.service=xhttp3xui-svc
      - traefik.http.routers.xhttp3xui-l4.priority=9999
      - traefik.http.routers.xhttp3xui-l4.observability.accessLogs=false

      # ---------- L4 / TCP / UDP маршруты ----------
      # VLESS Reality passthrough
      - traefik.tcp.routers.vless-reality.entrypoints=l4tcp
      - traefik.tcp.routers.vless-reality.rule=HostSNI(`${WEBDOMAIN}`)
      - traefik.tcp.routers.vless-reality.tls.passthrough=true
      - traefik.tcp.routers.vless-reality.service=vless-reality-svc
      - traefik.tcp.routers.vless-reality.priority=50

      # Backend порт для VLESS Reality
      - traefik.tcp.services.vless-reality-svc.loadbalancer.server.port=${PORT_LOCAL_VISION}
