services:
  sub2sing:
    image: ghcr.io/legiz-ru/sub2sing-box:latest
    container_name: sub2sing
    restart: unless-stopped
    extra_hosts:
      - ${WEBDOMAIN}:${PUBLIC_IPV4}
    networks:
      - traefik-proxy
      - dns-net
    # dns:
    #   - 172.31.0.53
