services:
  lampac:
    image: immisterio/lampac:latest
    container_name: lampac
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    mem_reservation: 1g
    mem_limit: 2g
    cpus: "1.0"
    healthcheck:
      test:
        - CMD
        - curl
        - -fs
        - http://127.0.0.1:9118
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    depends_on:
      traefik:
        condition: service_healthy
    env_file:
      - /opt/docker-proxy/.env
    volumes:
      - lampac_cache:/home/cache
      - /opt/docker-proxy/lampac/home/init.conf:/home/init.conf:rw
      - /opt/docker-proxy/lampac/home/users.json:/home/users.json:rw
      - /opt/docker-proxy/lampac/home/passwd:/home/passwd:ro
      - /opt/docker-proxy/lampac/module/manifest.json:/home/module/manifest.json
      - /opt/docker-proxy/lampac/plugins/lampainit.js:/home/plugins/lampainit.my.js:ro
      - /opt/docker-proxy/lampac/plugins/invc-rch.js:/home/plugins/invc-rch.js:ro
      - /opt/docker-proxy/lampac/plugins/lampainit-invc.js:/home/plugins/lampainit-invc.my.js:ro
      - /opt/docker-proxy/lampac/wwwroot/profileIcons:/home/wwwroot/profileIcons
      - /opt/docker-proxy/lampac/wwwroot/js:/home/wwwroot/js
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.14
      dns-net:
        ipv4_address: 172.19.0.14
    dns:
      - 172.19.0.10
