services:
  lampac:
    image: immisterio/lampac:latest
    container_name: lampac
    restart: unless-stopped
    mem_reservation: 1g
    mem_limit: 2g
    cpus: 1.0
    # ulimits:  
    #   nofile:  
    #     soft: 65536  
    #     hard: 65536
    healthcheck:
      test:
        - CMD
        - curl
        - -fs
        - http://127.0.0.1:9118
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    depends_on:
      traefik:
        condition: service_healthy
    env_file:
      - /opt/docker-proxy/.env
    volumes:
      - lampac_cache:/home/cache
      - /opt/docker-proxy/lampac/home/init.conf:/home/init.conf:rw
      - /opt/docker-proxy/lampac/home/users.json:/home/users.json:rw
      - /opt/docker-proxy/lampac/home/passwd:/home/passwd:ro
      - /opt/docker-proxy/lampac/module/manifest.json:/home/module/manifest.json
      - /opt/docker-proxy/lampac/plugins/lampainit.js:/home/plugins/lampainit.my.js:ro
      - /opt/docker-proxy/lampac/plugins/invc-rch.js:/home/plugins/invc-rch.js:ro
      - /opt/docker-proxy/lampac/plugins/lampainit-invc.js:/home/plugins/lampainit-invc.my.js:ro
      - /opt/docker-proxy/lampac/wwwroot/profileIcons:/home/wwwroot/profileIcons
      - /opt/docker-proxy/lampac/wwwroot/js:/home/wwwroot/js
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.14
      dns-net:
        ipv4_address: 172.19.0.14
    dns:
      - 172.19.0.10

    labels:  
      # Базовая конфигурация  
      - traefik.enable=true  
      - traefik.docker.network=traefik-proxy  
      - traefik.tags=traefik  
      - traefik.http.services.lampac.loadbalancer.server.port=9118  
        
      # HTTP to HTTPS редирект (самый низкий приоритет)  
      - traefik.http.routers.lampac-http.rule=Host(`${WEBDOMAIN}`)  
      - traefik.http.routers.lampac-http.entrypoints=web  
      - traefik.http.routers.lampac-http.service=lampac  
      - traefik.http.routers.lampac-http.middlewares=https-redirect  
      - traefik.http.routers.lampac-http.priority=10  
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https  
        
      # Основной HTTPS маршрут (низкий приоритет, catch-all)  
      - traefik.http.routers.lampac-https.rule=Host(`${WEBDOMAIN}`)  
      - traefik.http.routers.lampac-https.entrypoints=websecure  
      - traefik.http.routers.lampac-https.tls=true  
      - traefik.http.routers.lampac-https.tls.certresolver=le  
      - traefik.http.routers.lampac-https.service=lampac  
      - traefik.http.routers.lampac-https.middlewares=lampac-headers  
      - traefik.http.routers.lampac-https.priority=20
              
      # Proxy маршруты  
      - traefik.http.routers.lampac-proxy.rule=Host(`${WEBDOMAIN}`) && PathRegexp(`^/(proxy|proxyimg|cub|tmdb)`)  
      - traefik.http.routers.lampac-proxy.entrypoints=websecure  
      - traefik.http.routers.lampac-proxy.tls=true  
      - traefik.http.routers.lampac-proxy.service=lampac  
      - traefik.http.routers.lampac-proxy.middlewares=lampac-headers  
      - traefik.http.routers.lampac-proxy.priority=30
              
      # API маршруты  
      - traefik.http.routers.lampac-api.rule=Host(`${WEBDOMAIN}`) && PathRegexp(`^/(lite|sisi|version|extensions)`)  
      - traefik.http.routers.lampac-api.entrypoints=websecure  
      - traefik.http.routers.lampac-api.tls=true  
      - traefik.http.routers.lampac-api.service=lampac  
      - traefik.http.routers.lampac-api.middlewares=lampac-headers  
      - traefik.http.routers.lampac-api.priority=40  
        
      # Плагины (JS файлы)  
      - traefik.http.routers.lampac-plugins.rule=Host(`${WEBDOMAIN}`) && PathRegexp(`^/.+\\.js$`)  
      - traefik.http.routers.lampac-plugins.entrypoints=websecure  
      - traefik.http.routers.lampac-plugins.tls=true  
      - traefik.http.routers.lampac-plugins.service=lampac  
      - traefik.http.routers.lampac-plugins.middlewares=lampac-headers  
      - traefik.http.routers.lampac-plugins.priority=50  
        
      # Админка  
      - traefik.http.routers.lampac-admin.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`/admin`)  
      - traefik.http.routers.lampac-admin.entrypoints=websecure  
      - traefik.http.routers.lampac-admin.tls=true  
      - traefik.http.routers.lampac-admin.service=lampac  
      - traefik.http.routers.lampac-admin.middlewares=lampac-headers  
      - traefik.http.routers.lampac-admin.priority=60  
              
      # WebSocket для RCH  
      - traefik.http.routers.lampac-ws.rule=Host(`${WEBDOMAIN}`) && PathRegexp(`^/(nws|ws)`)  
      - traefik.http.routers.lampac-ws.entrypoints=websecure  
      - traefik.http.routers.lampac-ws.tls=true  
      - traefik.http.routers.lampac-ws.service=lampac  
      - traefik.http.routers.lampac-ws.middlewares=lampac-headers  
      - traefik.http.routers.lampac-ws.priority=70
      
      # Статические JS файлы  
      - traefik.http.routers.lampac-static-js.rule=Host(`${WEBDOMAIN}`) && PathPrefix(`/js`)  
      - traefik.http.routers.lampac-static-js.entrypoints=websecure  
      - traefik.http.routers.lampac-static-js.tls=true  
      - traefik.http.routers.lampac-static-js.service=lampac  
      - traefik.http.routers.lampac-static-js.priority=80
              
      # Заголовки безопасности  
      - traefik.http.middlewares.lampac-headers.headers.customRequestHeaders.X-Forwarded-Proto=https  
      - traefik.http.middlewares.lampac-headers.headers.stsSeconds=31536000  
      - traefik.http.middlewares.lampac-headers.headers.browserXssFilter=true  
      - traefik.http.middlewares.lampac-headers.headers.contentTypeNosniff=true
